name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: |
          dotnet restore ./MiniApp.Libraries.sln -s https://api.nuget.org/v3/index.json
          dotnet build ./MiniApp.Libraries.sln
          dotnet test ./MiniApp.Libraries.sln --no-build --collect:"XPlat Code Coverage";
          
