name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: |
          dotnet restore MinimalFramework.sln -s https://www.nuget.org/api/v2/
          dotnet build MinimalFramework.sln
          dotnet test MinimalFramework.sln --no-build --collect:"XPlat Code Coverage";
          
